
import "./globals.css";
import AuthProvider  from "./context/AuthContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        {children}
         <Toaster position="top-center" reverseOrder={false} />
        </AuthProvider>
        
      </body>
    </html>
  );
}
